model_name: yolo11n.pt
data: yolo_data/data.yaml

epochs: 120
imgsz: 320
batch: 4
cache: true
patience: 20
plots: true

device: 0
workers: 8
optimizer: auto
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
save: true
save_period: -1
val: true
split: val
rect: false
cos_lr: false
close_mosaic: 10
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
